name: Build go-server-template
on: [push, pull_request]
env:
  IMAGE_NAME: go-server-template
jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        go-version: ['1.24']
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: go mod tidy
      - name: Build
        run: go build -tags=viper_bind_struct -o build/server ./
      - name: Run tests
        run: go test ./...
  golangci:
    name: lint
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        go-version: [ '1.24']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.5
          args: --timeout=5m
  container:
    permissions:
      packages: write
      contents: read
    needs: [build, golangci]
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.set_var.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - name: Set VERSION environment variable
        run: |
            echo "VERSION=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
            echo "${{ env.VERSION }}"
            echo "version=${{ env.VERSION }}" >> $GITHUB_OUTPUT
      - name: Get Version
        run: echo $VERSION
      - name: Build Docker container
        run: docker build -t ghcr.io/GoServerTemplate/${{ env.IMAGE_NAME }}:${{ env.VERSION }} -f container/service.Dockerfile .
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Tag image Latest
        if: github.ref == 'refs/heads/development'
        run: |
          docker tag ghcr.io/GoServerTemplate/${{ env.IMAGE_NAME }}:${{ env.VERSION }} ghcr.io/GoServerTemplate/${{ env.IMAGE_NAME }}:latest
          docker push ghcr.io/GoServerTemplate/${{ env.IMAGE_NAME }}:latest
      - name: Tag image Production Latest
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag ghcr.io/GoServerTemplate/${{ env.IMAGE_NAME }}:${{ env.VERSION }} ghcr.io/GoServerTemplate/${{ env.IMAGE_NAME }}:prod-latest
          docker push ghcr.io/GoServerTemplate/${{ env.IMAGE_NAME }}:prod-latest
      - name: Push image
        run: |
            docker push ghcr.io/GoServerTemplate/${{ env.IMAGE_NAME }}:${{ env.VERSION }}